# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5917706e2bf31901262b687712b9b6896071c2e2210244c35ca0d2b23c55f21e6ebc90932c628cfdeca6e3c57c69e5977da89b8a192913d8820d4e710bd632a3

test:
  secret_key_base: a45a40aa8677876a473e508519c49c2c26e4f8672321d51250d818cf70091fa114a0bfebbf015f8b010bce6db16b970453dfc6a2722489af84dea155861505d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
